### ISSUE TITLE
triangles colouring

### ISSUE THREAD

**Issue by kirilind** [OuiShare/OuiShare-Fest-2016#11]
There may be a problem with how the triangles.js is rendering colour inputs - output colours are very different from the expected.

Source colour codes from [codepen triangles generator](http://codepen.io/msurguy/pen/sbIio):

<img width="1091" alt="screen shot 2016-01-12 at 15 55 49" src="https://cloud.githubusercontent.com/assets/4502647/12267013/62ec4d54-b946-11e5-8693-fdc2f855349b.png">

Colour settings in triangles.js:
* SHA: 8b3693439ea877679138c59c6e38641e7de6f541

Result screenshot:
<img width="1571" alt="screen shot 2016-01-12 at 16 03 39" src="https://cloud.githubusercontent.com/assets/4502647/12267186/2be00cdc-b947-11e5-8467-21790891268d.png">

What could cause the colour difference? Does something in triangles.js overwrite the Mesh and Light Properties ?

**Comment by karnaud** [comment]
The code had changed yes.
We have put 3 lights instead of two
https://github.com/OuiShare/OuiShare-Fest-2016/blob/4969c261a60e592539246239ea1deab8f6c669ff/lib/assets/javascripts/triangles.js#L1710

For changing the colors, it's here : 
https://github.com/OuiShare/OuiShare-Fest-2016/blob/4969c261a60e592539246239ea1deab8f6c669ff/lib/assets/javascripts/triangles.js#L1586

**Comment by kirilind** [comment]
Solution: keep only one addLight
https://github.com/OuiShare/OuiShare-Fest-2016/commit/43ba8f0e8a421ad3784838adc0be3881cec3cf83

For the size of light, modify zOffset:
https://github.com/OuiShare/OuiShare-Fest-2016/commit/3cfbd475c188e80d1c80e58328bbf9ea7dbc6579
